# Generated by Django 5.2.7 on 2025-11-19 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Только русские буквы, минимум 2 символа.', regex='^[А-ЯЁа-яё]{2,}$')])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Только русские буквы, минимум 2 символа.', regex='^[А-ЯЁа-яё]{2,}$')])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message='Формат: +7 900 000 00 00 или 89000000000', regex='^(\\+7\\s?\\d{3}\\s?\\d{3}\\s?\\d{2}\\s?\\d{2}|8\\d{10})$')])),
            ],
            options={
                'unique_together': {('first_name', 'last_name', 'email', 'phone')},
            },
        ),
    ]
